using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace MapleWorldAssignment.Common.Protocol
{
    // Placeholder for generated protobuf code
    // In a real scenario, this file would be auto-generated by protoc.
    // Here we manually implement the ChatMessage class to satisfy the requirement using Google.Protobuf.

    public sealed partial class ChatMessage : IMessage<ChatMessage>
    {
        private static readonly MessageParser<ChatMessage> _parser = new MessageParser<ChatMessage>(() => new ChatMessage());
        public static MessageParser<ChatMessage> Parser => _parser;

        public int UserId { get; set; }
        public string Content { get; set; } = "";

        public void WriteTo(CodedOutputStream output)
        {
            if (UserId != 0)
            {
                output.WriteRawTag(8);
                output.WriteInt32(UserId);
            }
            if (Content.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Content);
            }
        }

        public int CalculateSize()
        {
            int size = 0;
            if (UserId != 0)
            {
                size += 1 + CodedOutputStream.ComputeInt32Size(UserId);
            }
            if (Content.Length != 0)
            {
                size += 1 + CodedOutputStream.ComputeStringSize(Content);
            }
            return size;
        }

        public void MergeFrom(ChatMessage other)
        {
            if (other == null)
            {
                return;
            }
            if (other.UserId != 0)
            {
                UserId = other.UserId;
            }
            if (other.Content.Length != 0)
            {
                Content = other.Content;
            }
        }

        public void MergeFrom(CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch(tag) {
                    case 8: {
                        UserId = input.ReadInt32();
                        break;
                    }
                    case 18: {
                        Content = input.ReadString();
                        break;
                    }
                    default:
                        input.SkipLastField();
                        break;
                }
            }
        }

        public bool Equals(ChatMessage other)
        {
            if (ReferenceEquals(other, null)) {
                return false;
            }
            if (ReferenceEquals(other, this)) {
                return true;
            }
            if (UserId != other.UserId) return false;
            if (Content != other.Content) return false;
            return true;
        }

        public override bool Equals(object? obj)
        {
            return Equals(obj as ChatMessage);
        }

        public override int GetHashCode()
        {
            int hash = 1;
            if (UserId != 0) hash ^= UserId.GetHashCode();
            if (Content.Length != 0) hash ^= Content.GetHashCode();
            return hash;
        }

        public override string ToString()
        {
            return $"ChatMessage: {{ UserId: {UserId}, Content: {Content} }}";
        }

        public ChatMessage Clone()
        {
            return new ChatMessage
            {
                UserId = UserId,
                Content = Content
            };
        }

        MessageDescriptor? IMessage.Descriptor => null; // Placeholder, strict protobuf usage usually requires this.
    }
}
